[package]
name = "nekoton"
version = "0.1.0"
authors = [
    "Vladimir Petrzhikovskiy <v.petrzhikovskiy@dexpa.io>",
    "Ivan Kalinin <i.kalinin@dexpa.io>"
]
edition = "2018"

[dependencies]
aes-ctr = "0.6"
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.13"
chacha20poly1305 = "0.7.1"
chrono = "0.4.19"
curve25519-dalek = "3.0"
downcast-rs = "1.2"
dyn-clone = "1.0"
ed25519-dalek = "1.0"
failure = "0.1.8"
futures = "0.3"
getrandom = "0.1"
graphql_client = "0.9"
hex = "0.4"
log = "0.4"
num-bigint = { version = "0.2", features = ["serde"] }
num-traits = "0.2.14"
once_cell = "1.7"
parking_lot = "0.11.1"
pin-project-lite = "0.2"
rand = { version = "0.7", features = ["getrandom"] }
ring = "0.16"
secstr = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
thiserror = "1.0"
tiny-bip39 = "0.8.0"
tiny-hderive = "0.3.0"
tokio = { version = "1.4", default-features = false, features = ["sync"] }
x25519-dalek = "1.1"
zeroize = "1.2.0"

ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi.git" }
ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", branch = "original", package = "ton_api" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_executor = { git = "https://github.com/broxus/ton-labs-executor.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }
ton_vm = { git = "https://github.com/broxus/ton-labs-vm.git" }
tiny-jsonrpc = { version = "0.5.0", default-features = false }

[dev-dependencies]
cargo-husky = { version = "1", features = ["default", "run-cargo-fmt", "run-cargo-check"] }
criterion = { version = "0.3", features = ["async_tokio", "html_reports"] }
hex = "0.4.3"
pretty_assertions = "0.7.1"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.3", features = ["gzip"] }

[features]
default = []
integration_test = []
std = []
web = ["chrono/wasmbind", "getrandom/wasm-bindgen", "parking_lot/wasm-bindgen"]

[[bench]]
name = "words"
harness = false
