[package]
name = "nekoton"
version = "0.1.0"
authors = [
    "Vladimir Petrzhikovskiy <v.petrzhikovskiy@dexpa.io>",
    "Ivan Kalinin <i.kalinin@dexpa.io>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
aes-ctr = "0.6"
base64 = "0.13"
num-bigint = "0.2"
curve25519-dalek = "3.0"
chacha20poly1305 = "0.7.1"
ed25519-dalek = "1.0"
dyn-clone = "1.0"
graphql_client = "0.9"
hex = "0.4"
futures = "0.3"
once_cell = "1.7"
parking_lot = "0.11.1"
pin-project-lite = "0.2"
rand = { version = "0.7", features = ["getrandom"] }
ring = "0.16"
secstr = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
thiserror = "1.0"
tiny-hderive = "0.3.0"
tiny-bip39 = "0.8.0"
tokio = { version = "1.4", default-features = false, features = ["sync"] }

x25519-dalek = "1.1"
getrandom = "0.1"

num-traits = "0.2.14"

ton_api = { git = "https://github.com/broxus/ton-labs-tl.git", branch = "original", package = "ton_api" }

ton_abi = { git = "https://github.com/tonlabs/ton-labs-abi.git" }
ton_block = { git = "https://github.com/tonlabs/ton-labs-block.git" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }
ton_vm = { git = "https://github.com/broxus/ton-labs-vm.git" }
ton_executor = {git = "https://github.com/broxus/ton-labs-executor.git"}
failure = "0.1.8"
chrono = "0.4.19"

[dev-dependencies]
pretty_assertions = "0.7.1"
hex = "0.4.3"
criterion = "0.3"

[features]
default = []
std = []
web = ["chrono/wasmbind", "getrandom/wasm-bindgen", "parking_lot/wasm-bindgen"]

[target.'cfg(not(target_arch = "wasm32"))'.features]
default = ["std"]

[target.'cfg(target_arch = "wasm32")'.features]
default = ["web"]


[[bench]]
name = "words"
harness = false